version: '3.8'

services:
  app:
    build:
      context: ../
      dockerfile: docker/DockerFile
    ports:
      - "8000:8000"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_HOST: ${POSTGRES_HOST}
    depends_on:
      - db
    volumes:
      - ..:/app 
    command: sh -c "python setup.py sdist bdist_wheel && pip install -r requirements.txt && uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload"


  db:
    image: postgres:15.2
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_HOST: ${POSTGRES_HOST}
    volumes:
      - ../pgdata:/var/lib/postgresql/data

